#encoding:utf8
SPACE = "SPACE"
WORD = "WORD"
NUMBER = "NUMBER"
LEFT_PARENTHESE = "LEFT_PARENTHESE"
RIGHT_PARENTHESE = "RIGHT_PARENTHESE" 
POINT = "POINT"
STAR = "STAR"
SPACE = "SPACE"
COLON = "COLON"
EOF = "EOF"
BREAK = "BREAK"


